### ISSUE TITLE
ODK XLSForm management (PoC)

### ISSUE THREAD

**Issue by Thaliehln** [Research-IT-Swiss-TPH/odk_xlsform_management#1]
# Overview

Proof-of-Concept for handling various additional functions needed by ODK users for form design and analysis in complex projects

# Tasks

- [x] Transfer initial repo to Research-IT (compare function demo only): [https://github.com/Research-IT-Swiss-TPH/odk_xlsform_management](https://github.com/Research-IT-Swiss-TPH/odk_xlsform_management)

These comparisons will include as a minimal set:
- [x] Changes in the XLSForm settings tab
  - [x] updates to form ID, version, default language, and other metadata
- [x] Changes in the XLSForm choices tab (pre-defined answers)
  - [x] New answer options (list_name/name) added/removed
  - [x] Modifications to the phrasing or translation of existing choices
  - [x] Changes to cascading selections 
- [x] Changes in the XLSForm survey tab
  - [x] Groups added/removed
  - [x] Variables added/removed
  - [x] Changes to whether variables are mandatory
  - [x] Variables moved within the same group/to different groups
  - [x] Changes to the phrasing/translation of existing variable labels
  - [x] Changes to skip logic for existing variables
  - [x] Modifications to filtering rules
  - [x] Modifications to calculations
